dropwizard-jobs/dropwizard-jobs

dropwizard-jobs-core/pom.xml, dropwizard-jobs-guice/pom.xml, dropwizard-jobs-spring/pom.xml, pom.xml
Changed the pom version and removed the SNAPSHOT.
so we can publish to maven
=> pom version remove SNAPSHOT. new version is 1.0.0

dropwizard-jobs-core/pom.xml, pom.xml
Added scm to pom, as maven central requests.
=> add scm element in pom

.travis.yml, dropwizard-jobs-core/pom.xml, dropwizard-jobs-guice/pom.xml, dropwizard-jobs-spring/pom.xml, pom.xml
I added developer and contributors to the pom file.
Added more necessary tags.
http://central.sonatype.org/pages/requirements.html
Also, I suggest creating Sonatype JIRA accounts
http://central.sonatype.org/pages/ossrh-guide.html
Already created the ticket for deployment:
https://issues.sonatype.org/browse/OSSRH-15081
I added travis yml file so we can setup CI for the project.
=> pom modification in order to comply maven central deployment

pom.xml
Already deployed to sonatype.
https://issues.sonatype.org/browse/OSSRH-15081
I added some plugins to parent in order to deploy.
=> add plugins: source, javadoc, sonatype, gpg under release profile

README.md, dropwizard-jobs-core/pom.xml, dropwizard-jobs-guice/README.md, dropwizard-jobs-guice/pom.xml, dropwizard-jobs-spring/pom.xml, pom.xml
Fix dependencies is sub modules.
increase pom version to 1.0.1
readme modification
=> fix issue #24

README.md, dropwizard-jobs-core/src/main/java/de/spinscale/dropwizard/jobs/JobManager.java, dropwizard-jobs-core/src/main/java/de/spinscale/dropwizard/jobs/annotations/Every.java, dropwizard-jobs-core/src/main/java/de/spinscale/dropwizard/jobs/parser/TimeParserUtil.java, dropwizard-jobs-core/src/test/java/de/spinscale/dropwizard/jobs/EveryTestJobAlternativeConfiguration.java, dropwizard-jobs-core/src/test/java/de/spinscale/dropwizard/jobs/EveryTestJobDefaultConfiguration.java, dropwizard-jobs-core/src/test/java/de/spinscale/dropwizard/jobs/JobManagerTest.java, dropwizard-jobs-guice/src/main/java/de/spinscale/dropwizard/jobs/GuiceJobsBundle.java
Hi, I didn't want to rebuild the app every time I wanted to change the interval for my @Every jobs, so I have implemented a way of configuring it in the config file instead. Hopefully the README explains it all. There is a small amount of boilerplate required to make it work, any ideas to reduce it gratefully received. This could easily be extended to @On jobs too if you like it, though that's not implemented yet.
=> @Every jobs configurable via YAML

.travis.yml, README.md, dropwizard-jobs-core/pom.xml, dropwizard-jobs-guice/pom.xml, dropwizard-jobs-spring/pom.xml, pom.xml
@spinscale can you please activate Travis-CI repo at https://travis-ci.org/spinscale/dropwizard-jobs?
=> Version up and Travis CI integration

README.md, dropwizard-jobs-core/src/main/java/de/spinscale/dropwizard/jobs/DefaultQuartzConfiguration.java, dropwizard-jobs-core/src/main/java/de/spinscale/dropwizard/jobs/JobConfiguration.java, dropwizard-jobs-core/src/main/java/de/spinscale/dropwizard/jobs/JobManager.java, dropwizard-jobs-core/src/main/java/de/spinscale/dropwizard/jobs/JobsBundle.java, dropwizard-jobs-core/src/test/java/de/spinscale/dropwizard/jobs/JobManagerTest.java, dropwizard-jobs-guice/src/main/java/de/spinscale/dropwizard/jobs/GuiceJobManager.java, dropwizard-jobs-guice/src/main/java/de/spinscale/dropwizard/jobs/GuiceJobsBundle.java, dropwizard-jobs-guice/src/test/java/de/spinscale/dropwizard/jobs/GuiceJobManagerTest.java, dropwizard-jobs-spring/src/main/java/de/spinscale/dropwizard/jobs/SpringJobManager.java, dropwizard-jobs-spring/src/main/java/de/spinscale/dropwizard/jobs/SpringJobsBundle.java, dropwizard-jobs-spring/src/test/java/de/spinscale/dropwizard/jobs/SpringJobManagerTest.java
Hey, as stated in #50 I provided a PR. We are going to need it anyway, so I thought I'd just give it a shot. 
Feedback is very welcome. Sorry for some formatting issues...
=> Configure quartz configuration via dropwizard

dropwizard-jobs-guice/README.md
you can check at http://search.maven.org/#search%7Cga%7C1%7Cdropwizard-jobs-guice
=> fix groupId

README.md
This looks like a very handy bundle, but I was stumped by initial setup and the changes I needed to make to configuration. Judging by #61 and #48, I'm not alone in that.
This PR (hopefully) clarifies the initial instructions in README to make it a little easier to get started.
=> Documentation: clarify initial setup instructions

README.md
Update the readme file to contains updates coming from PR #66 and #68
=> Update readme file to contains latest changes

CHANGELOG.md, README.md, dropwizard-jobs-core/pom.xml, dropwizard-jobs-guice/README.md, dropwizard-jobs-guice/pom.xml, dropwizard-jobs-spring/pom.xml, pom.xml
bumping major version because of the major breaking changes in #56
=> bump version to 4.0.0-SNAPSHOT

README.md, dropwizard-jobs-core/pom.xml, dropwizard-jobs-guice/README.md, dropwizard-jobs-guice/pom.xml, dropwizard-jobs-spring/pom.xml, pom.xml
see https://issues.sonatype.org/browse/OSSRH-39526 for details
=> rename groupId according to the sonatype guidelines

pom.xml
=> upgrade to quartz.version 2.3.1

pom.xml
=> upgrade to dropwizard.version 1.3.11

pom.xml
=> upgrade to guice.version 4.2.2

pom.xml
=> upgrade to spring.version 5.0.14

.travis.yml
support multiple openjdk versions on build
=> support multiple jdks

pom.xml
=> explicitly use c3p0 v0.9.5.4

dropwizard-jobs-core/pom.xml, dropwizard-jobs-guice/pom.xml, dropwizard-jobs-spring/pom.xml, pom.xml
=> version 4.0.0-RC2

.travis.yml
Remove spaces as stated by https://www.codefactor.io/repository/github/dropwizard-jobs/dropwizard-jobs/issues
=> Remove Trailing spaces

.gitignore, .travis.yml
test coverage will be reported to codeclimate 
a corresponding badge is already in README
=> report test coverage to codeclimate

dropwizard-jobs-core/src/main/java/io/dropwizard/jobs/Hk2JobsBundle.java, dropwizard-jobs-core/src/main/java/io/dropwizard/jobs/JobConfiguration.java, dropwizard-jobs-core/src/main/java/io/dropwizard/jobs/JobManager.java, dropwizard-jobs-core/src/main/java/io/dropwizard/jobs/JobsBundle.java, dropwizard-jobs-core/src/test/java/io/dropwizard/jobs/AbstractJob.java, dropwizard-jobs-core/src/test/java/io/dropwizard/jobs/EveryTestJobWithSameJobName.java, dropwizard-jobs-core/src/test/java/io/dropwizard/jobs/Hk2JobsBundleTest.java, dropwizard-jobs-core/src/test/java/io/dropwizard/jobs/JobsBundleTest.java, dropwizard-jobs-guice/src/main/java/io/dropwizard/jobs/GuiceJobManager.java, dropwizard-jobs-guice/src/main/java/io/dropwizard/jobs/GuiceJobsBundle.java, dropwizard-jobs-guice/src/test/java/io/dropwizard/jobs/ApplicationStartTestJob.java, dropwizard-jobs-guice/src/test/java/io/dropwizard/jobs/ApplicationStopTestJob.java, dropwizard-jobs-guice/src/test/java/io/dropwizard/jobs/DependencyTestJob.java, dropwizard-jobs-guice/src/test/java/io/dropwizard/jobs/EveryTestJob.java, dropwizard-jobs-guice/src/test/java/io/dropwizard/jobs/GuiceJobsBundleTest.java, dropwizard-jobs-guice/src/test/java/io/dropwizard/jobs/OnTestJob.java, dropwizard-jobs-spring/src/main/java/io/dropwizard/jobs/SpringJobManager.java, dropwizard-jobs-spring/src/main/java/io/dropwizard/jobs/SpringJobsBundle.java, dropwizard-jobs-spring/src/test/java/io/dropwizard/jobs/ApplicationStartTestJob.java, dropwizard-jobs-spring/src/test/java/io/dropwizard/jobs/ApplicationStopTestJob.java, dropwizard-jobs-spring/src/test/java/io/dropwizard/jobs/DependencyTestJob.java, dropwizard-jobs-spring/src/test/java/io/dropwizard/jobs/EveryTestJob.java, dropwizard-jobs-spring/src/test/java/io/dropwizard/jobs/OnTestJob.java, dropwizard-jobs-spring/src/test/java/io/dropwizard/jobs/SpringJobsBundleTest.java, pom.xml
Updated to dropwizard 3.0.0, and guicey 6.0.0. Also replaced joda.time by java.time and removed unused imports
=> Updated to Dropwizard 3

README.md
=> updated README to prevent confusion

README.md
=> Update instructions about JobConfiguration in README

dropwizard-jobs-core/src/test/java/io/dropwizard/jobs/Hk2JobsBundleTest.java, pom.xml
These changes should allow dropwizard to be updated to version 4.0.4. Haven't contributed to a project before so let me know if I missed something.
=> BREAKING: Update dropwizard to 4.0.4
